# List of the Java classes that have been aspectized and name of the aspect classes separated by comma
	org.tetrabox.example.minitl.Binding = org.tetrabox.example.minitl.semantics.BindingAspect
	org.tetrabox.example.minitl.Transformation = org.tetrabox.example.minitl.semantics.TransformationAspect
	minitl.Transformation = org.tetrabox.example.minitl.semantics.TransformationAspect
	minitl.StringValue = org.tetrabox.example.minitl.semantics.StringValueAspect
	minitl.ObjectTemplate = org.tetrabox.example.minitl.semantics.ObjectTemplateAspect
	org.tetrabox.example.minitl.ObjectTemplate = org.tetrabox.example.minitl.semantics.ObjectTemplateAspect
	org.tetrabox.example.minitl.FieldAccessValue = org.tetrabox.example.minitl.semantics.FieldAccessValueAspect
	minitl.Rule = org.tetrabox.example.minitl.semantics.RuleAspect
	minitl.FieldAccessValue = org.tetrabox.example.minitl.semantics.FieldAccessValueAspect
	minitl.ObjectTemplateValue = org.tetrabox.example.minitl.semantics.ObjectTemplateValueAspect
	minitl.Value = org.tetrabox.example.minitl.semantics.ValueAspect
	org.tetrabox.example.minitl.Rule = org.tetrabox.example.minitl.semantics.RuleAspect
	org.tetrabox.example.minitl.ObjectTemplateValue = org.tetrabox.example.minitl.semantics.ObjectTemplateValueAspect
	minitl.Binding = org.tetrabox.example.minitl.semantics.BindingAspect
	org.tetrabox.example.minitl.Value = org.tetrabox.example.minitl.semantics.ValueAspect
	org.tetrabox.example.minitl.BinaryExpression = org.tetrabox.example.minitl.semantics.BinaryExpressionAspect
	minitl.BinaryExpression = org.tetrabox.example.minitl.semantics.BinaryExpressionAspect
	org.tetrabox.example.minitl.StringValue = org.tetrabox.example.minitl.semantics.StringValueAspect