/*
 * generated by Xtext 2.25.0
 */
package org.tetrabox.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.tetrabox.example.minitl.tcs.ui.internal.TcsActivator;

public class MinitlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TcsActivator.getInstance().getInjector("org.tetrabox.example.Minitl");
	}

}
