/*
 * generated by Xtext 2.25.0
 */
package org.tetrabox.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MinitlUiModule extends AbstractMinitlUiModule {

	public MinitlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
