/*
 * generated by Xtext 2.25.0
 */
package org.tetrabox.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.tetrabox.example.minitl.tcs.ui.internal.TcsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MinitlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TcsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TcsActivator activator = TcsActivator.getInstance();
		return activator != null ? activator.getInjector(TcsActivator.ORG_TETRABOX_EXAMPLE_MINITL) : null;
	}

}
